#!/bin/bash

echo "TURTLEBOT3_MODEL: $TURTLEBOT3_MODEL"
echo "TURTLEBOT3_NAME: $TURTLEBOT3_NAME"
echo "TURTLEBOT3_IP: $TURTLEBOT3_IP"
echo "TURTLEBOT3_NUMBER: $TURTLEBOT3_NUMBER"
echo "ROS_MASTER_URI: $ROS_MASTER_URI"
echo "ROS_HOSTNAME: $ROS_HOSTNAME"
echo "ROS_IP: $ROS_IP"